version: '3.8'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: 
