# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import classificator_pb2 as classificator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in classificator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassificatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/classificator.Classificator/Register',
                request_serializer=classificator__pb2.Nothing.SerializeToString,
                response_deserializer=classificator__pb2.Token.FromString,
                _registered_method=True)
        self.GetSample = channel.unary_unary(
                '/classificator.Classificator/GetSample',
                request_serializer=classificator__pb2.Token.SerializeToString,
                response_deserializer=classificator__pb2.Sample.FromString,
                _registered_method=True)
        self.SubmitSample = channel.unary_unary(
                '/classificator.Classificator/SubmitSample',
                request_serializer=classificator__pb2.SubmitSampleRequest.SerializeToString,
                response_deserializer=classificator__pb2.Nothing.FromString,
                _registered_method=True)
        self.GetFlag = channel.unary_unary(
                '/classificator.Classificator/GetFlag',
                request_serializer=classificator__pb2.Token.SerializeToString,
                response_deserializer=classificator__pb2.FlagResult.FromString,
                _registered_method=True)


class ClassificatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassificatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=classificator__pb2.Nothing.FromString,
                    response_serializer=classificator__pb2.Token.SerializeToString,
            ),
            'GetSample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSample,
                    request_deserializer=classificator__pb2.Token.FromString,
                    response_serializer=classificator__pb2.Sample.SerializeToString,
            ),
            'SubmitSample': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSample,
                    request_deserializer=classificator__pb2.SubmitSampleRequest.FromString,
                    response_serializer=classificator__pb2.Nothing.SerializeToString,
            ),
            'GetFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlag,
                    request_deserializer=classificator__pb2.Token.FromString,
                    response_serializer=classificator__pb2.FlagResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classificator.Classificator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('classificator.Classificator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Classificator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/classificator.Classificator/Register',
            classificator__pb2.Nothing.SerializeToString,
            classificator__pb2.Token.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/classificator.Classificator/GetSample',
            classificator__pb2.Token.SerializeToString,
            classificator__pb2.Sample.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/classificator.Classificator/SubmitSample',
            classificator__pb2.SubmitSampleRequest.SerializeToString,
            classificator__pb2.Nothing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/classificator.Classificator/GetFlag',
            classificator__pb2.Token.SerializeToString,
            classificator__pb2.FlagResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
