# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classificator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'classificator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63lassificator.proto\x12\rclassificator\"\t\n\x07Nothing\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\x06Sample\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\"\xb8\x01\n\x13SubmitSampleRequest\x12#\n\x05token\x18\x01 \x01(\x0b\x32\x14.classificator.Token\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12@\n\x0eprobable_class\x18\x03 \x01(\x0e\x32(.classificator.SubmitSampleRequest.Class\"-\n\x05\x43lass\x12\x0c\n\x08NEGATIVE\x10\x00\x12\x0c\n\x08POSITIVE\x10\x01\x12\x08\n\x04SPAM\x10\x02\"\x1d\n\nFlagResult\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8b\x02\n\rClassificator\x12\x38\n\x08Register\x12\x16.classificator.Nothing\x1a\x14.classificator.Token\x12\x38\n\tGetSample\x12\x14.classificator.Token\x1a\x15.classificator.Sample\x12J\n\x0cSubmitSample\x12\".classificator.SubmitSampleRequest\x1a\x16.classificator.Nothing\x12:\n\x07GetFlag\x12\x14.classificator.Token\x1a\x19.classificator.FlagResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classificator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTHING']._serialized_start=38
  _globals['_NOTHING']._serialized_end=47
  _globals['_TOKEN']._serialized_start=49
  _globals['_TOKEN']._serialized_end=71
  _globals['_SAMPLE']._serialized_start=73
  _globals['_SAMPLE']._serialized_end=111
  _globals['_SUBMITSAMPLEREQUEST']._serialized_start=114
  _globals['_SUBMITSAMPLEREQUEST']._serialized_end=298
  _globals['_SUBMITSAMPLEREQUEST_CLASS']._serialized_start=253
  _globals['_SUBMITSAMPLEREQUEST_CLASS']._serialized_end=298
  _globals['_FLAGRESULT']._serialized_start=300
  _globals['_FLAGRESULT']._serialized_end=329
  _globals['_CLASSIFICATOR']._serialized_start=332
  _globals['_CLASSIFICATOR']._serialized_end=599
# @@protoc_insertion_point(module_scope)
